name: CI Nuget Package

on: workflow_dispatch

jobs:
  build:
  
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      - name: setup dotnet
      - uses: actions/setup-dotnet@v4
        with: 
          dotnet-version: 9.0.100 
      - name: install dependencies
        run: ls -la
