name: CI Nuget Package

on: workflow_dispatch

jobs:
  build:  
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with: 
          dotnet-version: 9.0.100 
      - name: Install dependencies
        run: dotnet restore src/L.EventBus.Core/L.EventBus.Core.csproj
      - name: Build
        run: dotnet build --configuration Release --no-restore src/L.EventBus.Core/L.EventBus.Core.csproj
      - name: Package
        run: dotnet pack --configuration Release --no-restore --no-build src/L.EventBus.Core/L.EventBus.Core.csproj
      - name: Save package
        uses: actions/upload-artifact@v4
        with: 
          name: L.EventBus.Core.nupkg
          path: src/L.EventBus.Core/bin/Release/L.EventBus.Core.2.0.1.nupkg
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with: 
          dotnet-version: 9.0.100
      - name: Tests
        run: dotnet test --configuration Release tests/L.EventBus.Core.Tests/L.EventBus.Core.Tests.csproj
  publish:
    runs-on: ubuntu-latest
    needs: test
    env:
      api-key: ${{ secrets.NUGET_PACKAGE_ACCESS_TOKEN }}
    steps:
      - uses: actions/download-artifact@v4
        with: 
          name: L.EventBus.Core.nupkg
      - name: publish
        run: ls -la        
