name: CI Nuget Package

on: workflow_dispatch

jobs:
  build:  
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with: 
          dotnet-version: 9.0.100 
      - name: Install dependencies
        run: dotnet restore L.EventBus.sln
      - name: Build
        run: dotnet build --configuration Release --no-restore
